Erichard\DmsBundle\Entity\Document:
    type: entity
    repositoryClass: Erichard\DmsBundle\Entity\DocumentRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        filename:
            type: string
        name:
            type: string
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields: [name]
        type:
            type: string
        mimeType:
            type: string
            nullable: true
    manyToOne:
        node:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            inversedBy: documents
            joinColumn:
                onDelete: CASCADE

