Erichard\DmsBundle\Entity\Document:
    type: entity
    repositoryClass: Erichard\DmsBundle\Entity\DocumentRepository
    indexes:
        document_slug_idx:
            columns: [ slug ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        filename:
            type: string
        originalName:
            type: string
        name:
            type: string
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields: [name]
                    unique: true
                    updatable: true
        type:
            type: string
        mimeType:
            type: string
            nullable: true
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        node:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            inversedBy: documents
            joinColumn:
                onDelete: CASCADE
        parent:
            targetEntity: Erichard\DmsBundle\Entity\Document
            inversedBy: aliases
            joinColumn:
                onDelete: CASCADE
    oneToMany:
        metadatas:
            targetEntity: Erichard\DmsBundle\Entity\DocumentMetadata
            mappedBy: document
        aliases:
            targetEntity: Erichard\DmsBundle\Entity\Document
            mappedBy: parent

