Erichard\DmsBundle\Entity\DocumentNode:
    type: entity
    repositoryClass: Erichard\DmsBundle\Entity\DocumentNodeRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        slug:
          type: string
          length: 128
          gedmo:
            slug:
              fields: [name]
    manyToOne:
        parent:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            inversedBy: nodes
    oneToMany:
        nodes:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            mappedBy: parent
        documents:
            targetEntity: Erichard\DmsBundle\Entity\Document
            mappedBy: parent

