Erichard\DmsBundle\Entity\DocumentNodeMetadataLnk:
    type: entity
    table: dms__document_node_metadata__lnk
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    uniqueConstraints:
        node_metadata_idx:
            columns: [ node_id, metadata_id ]
    fields:
        value:
            type: text
    manyToOne:
        node:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            inversedBy: metadatas
            joinColumn:
                onDelete: CASCADE
        metadata:
            targetEntity: Erichard\DmsBundle\Entity\DocumentMetadata
            joinColumn:
                onDelete: CASCADE
