Erichard\DmsBundle\Entity\DocumentNodeAuthorization:
    type: entity
    readonly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    uniqueConstraints:
        node_authorization_idx:
            columns: [ role, node_id ]
    fields:
        role:
            type: string
            length: 50
        allow:
            type: integer
        deny:
            type: integer
    manyToOne:
        node:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            joinColumn:
                onDelete: CASCADE

