Erichard\DmsBundle\Entity\DocumentNode:
    type: entity
    repositoryClass: Erichard\DmsBundle\Entity\DocumentNodeRepository
    indexes:
        node_slug_idx:
            columns: [ slug ]
    gedmo:
        translation:
            locale: locale
        tree:
            type: closure
            closure: Erichard\DmsBundle\Entity\DocumentNodeClosure
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            gedmo:
                - translatable
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields: [name]
                    updatable: false
        depth:
            type: integer
            nullable: true
            gedmo:
                - treeLevel
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        parent:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            inversedBy: nodes
            joinColumn:
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        nodes:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            mappedBy: parent
            orderBy: {name: ASC}
        documents:
            targetEntity: Erichard\DmsBundle\Entity\Document
            mappedBy: node
            orderBy: {name: ASC}
        metadatas:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNodeMetadata
            mappedBy: node

