Erichard\DmsBundle\Entity\DocumentNode:
    type: entity
    repositoryClass: Erichard\DmsBundle\Entity\DocumentNodeRepository
    indexes:
        node_slug_idx:
            columns: [ slug ]
    gedmo:
        tree:
            type: closure
            closure: Erichard\DmsBundle\Entity\DocumentNodeClosure
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields: [name]
        depth:
            type: integer
            nullable: true
            gedmo:
                - treeLevel
        enabled:
            type: boolean
    manyToOne:
        parent:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            inversedBy: nodes
            joinColumn:
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        nodes:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            mappedBy: parent
        documents:
            targetEntity: Erichard\DmsBundle\Entity\Document
            mappedBy: node
        metadatas:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNodeMetadata
            mappedBy: node
            cascade: [ persist ]

