Erichard\DmsBundle\Entity\DocumentNode:
    type: entity
    repositoryClass: Erichard\DmsBundle\Repository\DocumentNodeRepository
    table: dms__document_node
    indexes:
        node_slug_idx:
            columns: [ slug ]
    gedmo:
        tree:
            type: closure
            closure: Erichard\DmsBundle\Entity\DocumentNodeClosure
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        uniqRef:
            type: string
            nullable: true
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields: [name]
                    updatable: false
        depth:
            type: integer
            nullable: true
            gedmo:
                - treeLevel
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        parent:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            inversedBy: nodes
            joinColumn:
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        nodes:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNode
            mappedBy: parent
        documents:
            targetEntity: Erichard\DmsBundle\Entity\Document
            mappedBy: node
        metadatas:
            targetEntity: Erichard\DmsBundle\Entity\DocumentNodeMetadataLnk
            mappedBy: node
