erichard_dms_node_home:
    pattern:  /dms
    defaults: { _controller: ErichardDmsBundle:Node:index }

erichard_dms_media_show:
    pattern:  /image/{dimension}/{path}.png
    defaults: { _controller: ErichardDmsBundle:Media:show }
    requirements:
        path: .*

##
# Document POST actions
#
erichard_dms_upload_document:
    pattern: /dms/upload
    defaults: { _controller: ErichardDmsBundle:Document:upload }
    methods: [POST]


##
# Folder Web actions
#
erichard_dms_node_list:
    pattern:  /dms/{node}
    defaults: { _controller: ErichardDmsBundle:Node:list }
    methods: [GET]

erichard_dms_add_node:
    pattern: /dms/{node}/new
    defaults: { _controller: ErichardDmsBundle:Node:add }
    methods: [GET]

erichard_dms_edit_node:
    pattern: /dms/{node}/edit
    defaults: { _controller: ErichardDmsBundle:Node:edit }
    methods: [GET]

erichard_dms_remove_node:
    pattern: /dms/{node}/remove
    defaults: { _controller: ErichardDmsBundle:Node:remove }
    methods: [GET]

##
# Folder POST actions
#
erichard_dms_create_node:
    pattern: /dms/{node}/new
    defaults: { _controller: ErichardDmsBundle:Node:create }
    methods: [POST]

erichard_dms_delete_node:
    pattern: /dms/{node}
    defaults: { _controller: ErichardDmsBundle:Node:delete }
    methods: [DELETE]

erichard_dms_update_node:
    pattern: /dms/{node}
    defaults: { _controller: ErichardDmsBundle:Node:update }
    methods: [POST]

##
# File Web actions
#
erichard_dms_add_document:
    pattern: /dms/{node}/add-document
    defaults: { _controller: ErichardDmsBundle:Document:add }
    methods: [GET]

erichard_dms_create_document:
    pattern: /dms/{node}/add-document
    defaults: { _controller: ErichardDmsBundle:Document:create }
    methods: [POST]

erichard_dms_show_document:
    pattern: /dms/{node}/{document}
    defaults: { _controller: ErichardDmsBundle:Document:show }
    methods: [GET]
