erichard_dms_node_home:
    pattern:  /
    defaults: { _controller: ErichardDmsBundle:Node:index }

erichard_dms_document_preview:
    pattern:  /{dimension}/{node}/{document}.png
    defaults: { _controller: ErichardDmsBundle:Document:preview }
    requirements:
        dimension: \d+x\d+

##
# Document POST actions
#
erichard_dms_upload_document:
    pattern: /upload
    defaults: { _controller: ErichardDmsBundle:Document:upload }
    requirements:
        _method: POST


##
# Folder Web actions
#
erichard_dms_node_list:
    pattern:  /{node}
    defaults: { _controller: ErichardDmsBundle:Node:list }
    requirements:
        _method: GET

erichard_dms_add_node:
    pattern: /{node}/new
    defaults: { _controller: ErichardDmsBundle:Node:add }
    requirements:
        _method: GET

erichard_dms_edit_node:
    pattern: /{node}/edit
    defaults: { _controller: ErichardDmsBundle:Node:edit }
    requirements:
        _method: GET

erichard_dms_remove_node:
    pattern: /{node}/remove
    defaults: { _controller: ErichardDmsBundle:Node:remove }
    requirements:
        _method: GET

##
# Folder POST actions
#
erichard_dms_create_node:
    pattern: /{node}/new
    defaults: { _controller: ErichardDmsBundle:Node:create }
    requirements:
        _method: POST

erichard_dms_delete_node:
    pattern: /{node}
    defaults: { _controller: ErichardDmsBundle:Node:delete }
    requirements:
        _method: DELETE

erichard_dms_update_node:
    pattern: /{node}
    defaults: { _controller: ErichardDmsBundle:Node:update }
    requirements:
        _method: POST

##
# File Web actions
#
erichard_dms_add_document:
    pattern: /{node}/add-document
    defaults: { _controller: ErichardDmsBundle:Document:add }
    requirements:
        _method: GET

erichard_dms_create_document:
    pattern: /{node}/add-document
    defaults: { _controller: ErichardDmsBundle:Document:create }
    requirements:
        _method: POST

erichard_dms_show_document:
    pattern: /{node}/{document}
    defaults: { _controller: ErichardDmsBundle:Document:show }
    requirements:
        _method: GET

erichard_dms_edit_document:
    pattern: /{node}/{document}/edit
    defaults: { _controller: ErichardDmsBundle:Document:edit }
    requirements:
        _method: GET

erichard_dms_update_document:
    pattern: /{node}/{document}
    defaults: { _controller: ErichardDmsBundle:Document:update }
    requirements:
        _method: POST

erichard_dms_download_document:
    pattern: /{node}/{document}/download
    defaults: { _controller: ErichardDmsBundle:Document:download }
    requirements:
        _method: GET


erichard_dms_remove_document:
    pattern: /{node}/{document}/remove
    defaults: { _controller: ErichardDmsBundle:Document:remove }
    requirements:
        _method: GET

erichard_dms_delete_document:
    pattern: /{node}/{document}
    defaults: { _controller: ErichardDmsBundle:Document:delete }
    requirements:
        _method: DELETE

# Link management
erichard_dms_link_document:
    pattern: /{node}/{document}/link
    defaults: { _controller: ErichardDmsBundle:Document:link }
    requirements:
        _method: POST|GET
