parameters:
    dms.storage.path: %kernel.root_dir%/../web/medias

services:
    erichard.twig.container_extension:
        class: Erichard\DmsBundle\Twig\ContainerExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    erichard.twig.dms_extension:
        class: Erichard\DmsBundle\Twig\DmsExtension
        arguments:
            - @doctrine
        tags:
            - { name: twig.extension }

    erichard.security.access.hierarchical_voter:
        class:      Erichard\DmsBundle\Security\Voter\HierarchicalAclVoter
        public:     false
        arguments:
            - @erichard.security.access.permission_map
            - @erichard.security.access.control_list
        tags:
            - { name: security.voter }

    erichard.security.access.permission_map:
        class: Erichard\DmsBundle\Security\Acl\Permission\DmsPermissionMap

    erichard.security.access.control_list:
        class: Erichard\DmsBundle\Security\Acl\Acl
        arguments:
            - @security.role_hierarchy
            - @doctrine.orm.entity_manager
            - { cache_dir: %kernel.cache_dir% }


    erichard.cache.permission_warmer:
        class: Erichard\DmsBundle\Cache\PermissionWarmer
        arguments:
            - @erichard.security.role_provider
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.cache_warmer }

    erichard.security.role_provider:
        class: Erichard\DmsBundle\Security\RoleProvider
        arguments:
            - @service_container


