parameters:
    dms.gallery.items_per_row: 4
    dms.gallery.image_size: 260x180
    dms.content.image_size: 190x80
    dms.list.image_size: 32x32
    dms.showcase.image_size: 870x400

    dms.storage.path: %kernel.root_dir%/../web/medias
    dms.storage.tmp_path: %kernel.root_dir%/tmp

services:
    erichard.twig.container_extension:
        class: Erichard\DmsBundle\Twig\ContainerExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    erichard.doctrine.document_listener:
        class: Erichard\DmsBundle\Listener\DocumentListener
        arguments:
            - %dms.storage.path%
        tags:
            - { name: doctrine.event_listener, event: postLoad }
