parameters:

    dms.storage.path: %kernel.root_dir%/../web/medias

services:
    erichard.twig.container_extension:
        class: Erichard\DmsBundle\Twig\ContainerExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    erichard.twig.dms_extension:
        class: Erichard\DmsBundle\Twig\DmsExtension
        arguments:
            - @doctrine
        tags:
            - { name: twig.extension }

    erichard.doctrine.document_listener:
        class: Erichard\DmsBundle\Listener\DocumentListener
        arguments:
            - %dms.storage.path%
        tags:
            - { name: doctrine.event_listener, event: postLoad }
