parameters:
    dms.storage.path: %kernel.root_dir%/../web/medias

services:
    erichard.twig.container_extension:
        class: Erichard\DmsBundle\Twig\ContainerExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    erichard.security.access.hierarchical_voter:
        class:      Erichard\DmsBundle\Security\Voter\HierarchicalAclVoter
        public:     false
        arguments:
            - @erichard.security.access.permission_map
            - @erichard.security.access.control_list
        tags:
            - { name: security.voter }

    erichard.security.access.permission_map:
        class: Erichard\DmsBundle\Security\Acl\Permission\DmsPermissionMap

    erichard.security.access.control_list:
        class: Erichard\DmsBundle\Security\Acl\Acl
        arguments:
            - @security.role_hierarchy
            - @doctrine.orm.entity_manager
            - { cache_dir: %kernel.cache_dir%, super_admin_role: %dms.permission.super_admin_role% }

    erichard.security.role_provider:
        class: Erichard\DmsBundle\Security\RoleProvider
        arguments:
            - @service_container

    erichard.form.node_metadata_type:
        class: Erichard\DmsBundle\Form\NodeMetadataType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: node_metadata }

    erichard.form.document_metadata_type:
        class: Erichard\DmsBundle\Form\DocumentMetadataType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: document_metadata }
