parameters:
    dms.storage.path: %kernel.root_dir%/../web/medias
    dms.storage.web_path: %kernel.root_dir%/../web

services:
    dms.twig.container_extension:
        class: Erichard\DmsBundle\Twig\ContainerExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    dms.twig.dms_extension:
        class: Erichard\DmsBundle\Twig\DmsExtension
        arguments:
            - @router
            - @doctrine
        tags:
            - { name: twig.extension }

    dms.security.access.hierarchical_voter:
        class:      Erichard\DmsBundle\Security\Voter\HierarchicalAclVoter
        public:     false
        arguments:
            - @dms.security.access.permission_map
            - @dms.security.access.control_list
            - { permission_enabled: %dms.permission.enabled% }
        tags:
            - { name: security.voter }

    dms.security.access.permission_map:
        class: Erichard\DmsBundle\Security\Acl\Permission\DmsPermissionMap

    dms.security.access.control_list:
        class: Erichard\DmsBundle\Security\Acl\Acl
        arguments:
            - @security.role_hierarchy
            - @doctrine.orm.entity_manager
            - @session=
            - { cache_dir: %kernel.cache_dir%, super_admin_role: %dms.permission.super_admin_role% }

    dms.security.role_provider:
        class: Erichard\DmsBundle\Security\RoleProvider
        arguments:
            - @service_container

    dms.form.document_type:
        class: Erichard\DmsBundle\Form\DocumentType
        arguments:
            - %dms.storage.tmp_path%
        tags:
            - { name: form.type, alias: dms_document }

    dms.form.document_node_type:
        class: Erichard\DmsBundle\Form\NodeType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: dms_node }

    dms.form.node_selector_type:
        class: Erichard\DmsBundle\Form\NodeSelectorType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: dms_node_selector }

    dms.form.node_metadata_type:
        class: Erichard\DmsBundle\Form\NodeMetadataType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: node_metadata }

    dms.form.document_metadata_type:
        class: Erichard\DmsBundle\Form\DocumentMetadataType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: document_metadata }

    dms.repository.document:
        class: Erichard\DmsBundle\Entity\DocumentRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Erichard\DmsBundle\Entity\Document
        calls:
            - [ setSecurityContext, [ @security.context ]]

    dms.repository.documentNode:
        class: Erichard\DmsBundle\Entity\DocumentNodeRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Erichard\DmsBundle\Entity\DocumentNode
        calls:
            - [ setSecurityContext, [ @security.context ]]

    dms.manager:
        class:  Erichard\DmsBundle\DmsManager
        arguments:
            - @doctrine
            - @security.context
            - @dms.mime_type_manager
            - @router
            - { storage_path: %dms.storage.path%, web_path: %dms.storage.web_path }

    dms.mime_type_manager:
        class: Erichard\DmsBundle\MimeTypeManager
        arguments:
            - @kernel
