parameters:

    dms.storage.path: %kernel.root_dir%/../web/medias

services:
    erichard.twig.container_extension:
        class: Erichard\DmsBundle\Twig\ContainerExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    erichard.twig.dms_extension:
        class: Erichard\DmsBundle\Twig\DmsExtension
        arguments:
            - @doctrine
        tags:
            - { name: twig.extension }
